In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 19.2 MB/s  0:00:00eta 0:00:01
Downloading numpy-2.5.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 35.3 MB/s  0:00:00m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.5.0 pandas-3.0.3

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [ ]:
#importamos libreria
import pandas as pd

''

In [6]:
data = [['Juan',25],['Pedro',23],['Luis',45]]
df = pd.DataFrame(data)
df.head()

       0   1
0   Juan  25
1  Pedro  23
2   Luis  45

In [11]:
df = pd.read_csv('/workspaces/AnalisisDatosPy/sesion1/utils/utils/data/data.csv')
df.head()

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [13]:
df = pd.read_csv('/workspaces/AnalisisDatosPy/sesion1/utils/utils/data/data_without_header',
                 sep=',',
                 header=None
                 )
df.head()

       0   1          2
0   Juan  25     Madrid
1  María  30  Barcelona
2  Pedro  35    Sevilla

In [15]:
df = pd.read_json('/workspaces/AnalisisDatosPy/sesion1/utils/utils/data/data.json')
df.head()

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla